// INIT
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// COURSES
export const GET_COURSES = 'GET_COURSES';
export const GET_COURSE = 'GET_COURSE';
export const ADD_COURSE = 'ADD_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const COURSE_ERROR = 'COURSE_ERROR';

// REVIEWS
export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEW = 'GET_REVIEW';
export const ADD_REVIEW = 'ADD_REVIEW';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const REVIEW_ERROR = 'REVIEW_ERROR';

// AUTH
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const GET_RESET_TOKEN = 'GET_RESET_TOKEN';
export const UPDATE_ERROR = 'UPDATE_ERROR';

// BOOTCAMPS
export const GET_BOOTCAMPS = 'GET_BOOTCAMPS';
export const GET_BOOTCAMP = 'GET_BOOTCAMP';
export const ADD_BOOTCAMP = 'ADD_BOOTCAMP';
export const DELETE_BOOTCAMP = 'DELETE_BOOTCAMP';
export const UPDATE_BOOTCAMP = 'UPDATE_BOOTCAMP';
export const PHOTO_UPLOAD = 'PHOTO_UPLOAD';
export const BOOTCAMP_ERROR = 'BOOTCAMP_ERROR';
export const CLEAR_BOOTCAMP = 'CLEAR_BOOTCAMP';
export const CLEAR_BOOTCAMPS = 'CLEAR_BOOTCAMPS';


// USERS - PRIVATE/ADMIN
export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const ADD_USER = 'ADD_USER';
export const USERS_ERROR = 'USERS_ERROR';
export const USER_ERROR = 'USER_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
